### PR TITLE
support dr fr lr 100G

### PR DESCRIPTION
**Pull request by vjanandr**
support dr fr lr 100G

### CODE REVIEW

**Review by ashutosh-arrcus — APPROVED** [review]

**Comment by ashutosh-arrcus** [comment]
@sonoble : Can you please merge this PR? I am not able to merge the commit.

**Comment by sonoble** [comment]
Can you sign the commit? I believe that is what is blocking it.

**Comment by vjanandr** [comment]
pushed new commit after signing with the right key.

**Comment by ashutosh-arrcus** [comment]
@vjanandr / @sonoble : Merging, Thank you for taking care of this.

**Pull request merged**
