### PR TITLE
 Add vendor_revision property for sff

### PR DESCRIPTION
**Pull request by karthikeyan-arrcus**
Initializing a field vendor revision to sff.h file to add implement it's functionality in our code.
@sonoble @jnealtowns

### CODE REVIEW

**Comment by karthikeyan-arrcus** [comment]
Hii @sonoble, @jnealtowns.. Can u pls approve this PR asap..Need it for a priority issue

**Review by sonoble — COMMENTED** [review]
You started with 4 chars then changed it to 5, it would be cleaner if you submitted it as a single commit. Is there background on the addition of the new vendor revision property?

**Comment by karthikeyan-arrcus** [comment]
yep made a mistake initially with 4 chars..can the commit with 5 chars alone be merged?
It is a customer requirement and Here is the document that I referred to add the vendor_rev property - https://cdn.hackaday.io/files/21599924091616/AN_2030_DDMI_for_SFP_Rev_E2.pdf

**Comment by sonoble** [comment]
> yep made a mistake initially with 4 chars..can the commit with 5 chars alone be merged? It is a customer requirement and Here is the document that I referred to add the vendor_rev property - https://cdn.hackaday.io/files/21599924091616/AN_2030_DDMI_for_SFP_Rev_E2.pdf

No but you can should be able to diff, create a clean branch, apply diff and then sign it and submit it..

**Comment by karthikeyan-arrcus** [comment]
Okk then let me close this PR and create a new one with a clean branch

**Pull request closed without merging**
